/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppRoot {
        "history": RouterHistory;
    }
    interface CBanner {
        "theme": string;
    }
    interface CCard {
    }
    interface CPage {
    }
    interface CSidebar {
    }
    interface Demo1 {
    }
    interface Demo2 {
    }
    interface Demo3 {
    }
    interface Demo4 {
    }
    interface Demo5 {
    }
    interface Demo6 {
    }
    interface Demo7 {
    }
    interface Demo8 {
    }
    interface EButton {
        "action": string;
        "active": boolean;
        "disabled": boolean;
        "size": string;
        "value": any;
        "variant": string;
    }
    interface EInput {
        "checked": boolean;
        "label": string;
        "name": string;
        "placeholder": string;
        "type": string;
        "value": string;
    }
    interface ELink {
        "action": string;
        "event": boolean;
        "href": string;
        "target": string;
        "theme": string;
        "value": any;
        "variant": string;
    }
    interface EList {
    }
    interface EListItem {
    }
    interface ESelect {
        "name": string;
        "options": any;
    }
    interface EText {
        "theme": string;
        "variant": string;
    }
    interface LRow {
        "align": string;
        "justifyContent": string;
        "variant": string;
    }
    interface LSeperator {
    }
    interface LSpacer {
        "value": number;
        "variant": string;
    }
    interface PInfoItem {
    }
    interface PNodeCard {
        "isExpanded": boolean;
    }
    interface PNodeItem {
        "variant": string;
    }
    interface VCatchAll {
        "history": RouterHistory;
    }
    interface VHome {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCBannerElement extends Components.CBanner, HTMLStencilElement {
    }
    var HTMLCBannerElement: {
        prototype: HTMLCBannerElement;
        new (): HTMLCBannerElement;
    };
    interface HTMLCCardElement extends Components.CCard, HTMLStencilElement {
    }
    var HTMLCCardElement: {
        prototype: HTMLCCardElement;
        new (): HTMLCCardElement;
    };
    interface HTMLCPageElement extends Components.CPage, HTMLStencilElement {
    }
    var HTMLCPageElement: {
        prototype: HTMLCPageElement;
        new (): HTMLCPageElement;
    };
    interface HTMLCSidebarElement extends Components.CSidebar, HTMLStencilElement {
    }
    var HTMLCSidebarElement: {
        prototype: HTMLCSidebarElement;
        new (): HTMLCSidebarElement;
    };
    interface HTMLDemo1Element extends Components.Demo1, HTMLStencilElement {
    }
    var HTMLDemo1Element: {
        prototype: HTMLDemo1Element;
        new (): HTMLDemo1Element;
    };
    interface HTMLDemo2Element extends Components.Demo2, HTMLStencilElement {
    }
    var HTMLDemo2Element: {
        prototype: HTMLDemo2Element;
        new (): HTMLDemo2Element;
    };
    interface HTMLDemo3Element extends Components.Demo3, HTMLStencilElement {
    }
    var HTMLDemo3Element: {
        prototype: HTMLDemo3Element;
        new (): HTMLDemo3Element;
    };
    interface HTMLDemo4Element extends Components.Demo4, HTMLStencilElement {
    }
    var HTMLDemo4Element: {
        prototype: HTMLDemo4Element;
        new (): HTMLDemo4Element;
    };
    interface HTMLDemo5Element extends Components.Demo5, HTMLStencilElement {
    }
    var HTMLDemo5Element: {
        prototype: HTMLDemo5Element;
        new (): HTMLDemo5Element;
    };
    interface HTMLDemo6Element extends Components.Demo6, HTMLStencilElement {
    }
    var HTMLDemo6Element: {
        prototype: HTMLDemo6Element;
        new (): HTMLDemo6Element;
    };
    interface HTMLDemo7Element extends Components.Demo7, HTMLStencilElement {
    }
    var HTMLDemo7Element: {
        prototype: HTMLDemo7Element;
        new (): HTMLDemo7Element;
    };
    interface HTMLDemo8Element extends Components.Demo8, HTMLStencilElement {
    }
    var HTMLDemo8Element: {
        prototype: HTMLDemo8Element;
        new (): HTMLDemo8Element;
    };
    interface HTMLEButtonElement extends Components.EButton, HTMLStencilElement {
    }
    var HTMLEButtonElement: {
        prototype: HTMLEButtonElement;
        new (): HTMLEButtonElement;
    };
    interface HTMLEInputElement extends Components.EInput, HTMLStencilElement {
    }
    var HTMLEInputElement: {
        prototype: HTMLEInputElement;
        new (): HTMLEInputElement;
    };
    interface HTMLELinkElement extends Components.ELink, HTMLStencilElement {
    }
    var HTMLELinkElement: {
        prototype: HTMLELinkElement;
        new (): HTMLELinkElement;
    };
    interface HTMLEListElement extends Components.EList, HTMLStencilElement {
    }
    var HTMLEListElement: {
        prototype: HTMLEListElement;
        new (): HTMLEListElement;
    };
    interface HTMLEListItemElement extends Components.EListItem, HTMLStencilElement {
    }
    var HTMLEListItemElement: {
        prototype: HTMLEListItemElement;
        new (): HTMLEListItemElement;
    };
    interface HTMLESelectElement extends Components.ESelect, HTMLStencilElement {
    }
    var HTMLESelectElement: {
        prototype: HTMLESelectElement;
        new (): HTMLESelectElement;
    };
    interface HTMLETextElement extends Components.EText, HTMLStencilElement {
    }
    var HTMLETextElement: {
        prototype: HTMLETextElement;
        new (): HTMLETextElement;
    };
    interface HTMLLRowElement extends Components.LRow, HTMLStencilElement {
    }
    var HTMLLRowElement: {
        prototype: HTMLLRowElement;
        new (): HTMLLRowElement;
    };
    interface HTMLLSeperatorElement extends Components.LSeperator, HTMLStencilElement {
    }
    var HTMLLSeperatorElement: {
        prototype: HTMLLSeperatorElement;
        new (): HTMLLSeperatorElement;
    };
    interface HTMLLSpacerElement extends Components.LSpacer, HTMLStencilElement {
    }
    var HTMLLSpacerElement: {
        prototype: HTMLLSpacerElement;
        new (): HTMLLSpacerElement;
    };
    interface HTMLPInfoItemElement extends Components.PInfoItem, HTMLStencilElement {
    }
    var HTMLPInfoItemElement: {
        prototype: HTMLPInfoItemElement;
        new (): HTMLPInfoItemElement;
    };
    interface HTMLPNodeCardElement extends Components.PNodeCard, HTMLStencilElement {
    }
    var HTMLPNodeCardElement: {
        prototype: HTMLPNodeCardElement;
        new (): HTMLPNodeCardElement;
    };
    interface HTMLPNodeItemElement extends Components.PNodeItem, HTMLStencilElement {
    }
    var HTMLPNodeItemElement: {
        prototype: HTMLPNodeItemElement;
        new (): HTMLPNodeItemElement;
    };
    interface HTMLVCatchAllElement extends Components.VCatchAll, HTMLStencilElement {
    }
    var HTMLVCatchAllElement: {
        prototype: HTMLVCatchAllElement;
        new (): HTMLVCatchAllElement;
    };
    interface HTMLVHomeElement extends Components.VHome, HTMLStencilElement {
    }
    var HTMLVHomeElement: {
        prototype: HTMLVHomeElement;
        new (): HTMLVHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "c-banner": HTMLCBannerElement;
        "c-card": HTMLCCardElement;
        "c-page": HTMLCPageElement;
        "c-sidebar": HTMLCSidebarElement;
        "demo-1": HTMLDemo1Element;
        "demo-2": HTMLDemo2Element;
        "demo-3": HTMLDemo3Element;
        "demo-4": HTMLDemo4Element;
        "demo-5": HTMLDemo5Element;
        "demo-6": HTMLDemo6Element;
        "demo-7": HTMLDemo7Element;
        "demo-8": HTMLDemo8Element;
        "e-button": HTMLEButtonElement;
        "e-input": HTMLEInputElement;
        "e-link": HTMLELinkElement;
        "e-list": HTMLEListElement;
        "e-list-item": HTMLEListItemElement;
        "e-select": HTMLESelectElement;
        "e-text": HTMLETextElement;
        "l-row": HTMLLRowElement;
        "l-seperator": HTMLLSeperatorElement;
        "l-spacer": HTMLLSpacerElement;
        "p-info-item": HTMLPInfoItemElement;
        "p-node-card": HTMLPNodeCardElement;
        "p-node-item": HTMLPNodeItemElement;
        "v-catch-all": HTMLVCatchAllElement;
        "v-home": HTMLVHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
        "history"?: RouterHistory;
    }
    interface CBanner {
        "theme"?: string;
    }
    interface CCard {
    }
    interface CPage {
    }
    interface CSidebar {
    }
    interface Demo1 {
    }
    interface Demo2 {
    }
    interface Demo3 {
    }
    interface Demo4 {
    }
    interface Demo5 {
    }
    interface Demo6 {
    }
    interface Demo7 {
    }
    interface Demo8 {
    }
    interface EButton {
        "action"?: string;
        "active"?: boolean;
        "disabled"?: boolean;
        "onButtonClick"?: (event: CustomEvent<any>) => void;
        "size"?: string;
        "value"?: any;
        "variant"?: string;
    }
    interface EInput {
        "checked"?: boolean;
        "label"?: string;
        "name"?: string;
        "onTextInput"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface ELink {
        "action"?: string;
        "event"?: boolean;
        "href"?: string;
        "onEvent_LinkClick"?: (event: CustomEvent<any>) => void;
        "target"?: string;
        "theme"?: string;
        "value"?: any;
        "variant"?: string;
    }
    interface EList {
    }
    interface EListItem {
    }
    interface ESelect {
        "name"?: string;
        "onEvent_selectInput"?: (event: CustomEvent<any>) => void;
        "options"?: any;
    }
    interface EText {
        "theme"?: string;
        "variant"?: string;
    }
    interface LRow {
        "align"?: string;
        "justifyContent"?: string;
        "variant"?: string;
    }
    interface LSeperator {
    }
    interface LSpacer {
        "value"?: number;
        "variant"?: string;
    }
    interface PInfoItem {
    }
    interface PNodeCard {
        "isExpanded"?: boolean;
    }
    interface PNodeItem {
        "variant"?: string;
    }
    interface VCatchAll {
        "history"?: RouterHistory;
    }
    interface VHome {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "c-banner": CBanner;
        "c-card": CCard;
        "c-page": CPage;
        "c-sidebar": CSidebar;
        "demo-1": Demo1;
        "demo-2": Demo2;
        "demo-3": Demo3;
        "demo-4": Demo4;
        "demo-5": Demo5;
        "demo-6": Demo6;
        "demo-7": Demo7;
        "demo-8": Demo8;
        "e-button": EButton;
        "e-input": EInput;
        "e-link": ELink;
        "e-list": EList;
        "e-list-item": EListItem;
        "e-select": ESelect;
        "e-text": EText;
        "l-row": LRow;
        "l-seperator": LSeperator;
        "l-spacer": LSpacer;
        "p-info-item": PInfoItem;
        "p-node-card": PNodeCard;
        "p-node-item": PNodeItem;
        "v-catch-all": VCatchAll;
        "v-home": VHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "c-banner": LocalJSX.CBanner & JSXBase.HTMLAttributes<HTMLCBannerElement>;
            "c-card": LocalJSX.CCard & JSXBase.HTMLAttributes<HTMLCCardElement>;
            "c-page": LocalJSX.CPage & JSXBase.HTMLAttributes<HTMLCPageElement>;
            "c-sidebar": LocalJSX.CSidebar & JSXBase.HTMLAttributes<HTMLCSidebarElement>;
            "demo-1": LocalJSX.Demo1 & JSXBase.HTMLAttributes<HTMLDemo1Element>;
            "demo-2": LocalJSX.Demo2 & JSXBase.HTMLAttributes<HTMLDemo2Element>;
            "demo-3": LocalJSX.Demo3 & JSXBase.HTMLAttributes<HTMLDemo3Element>;
            "demo-4": LocalJSX.Demo4 & JSXBase.HTMLAttributes<HTMLDemo4Element>;
            "demo-5": LocalJSX.Demo5 & JSXBase.HTMLAttributes<HTMLDemo5Element>;
            "demo-6": LocalJSX.Demo6 & JSXBase.HTMLAttributes<HTMLDemo6Element>;
            "demo-7": LocalJSX.Demo7 & JSXBase.HTMLAttributes<HTMLDemo7Element>;
            "demo-8": LocalJSX.Demo8 & JSXBase.HTMLAttributes<HTMLDemo8Element>;
            "e-button": LocalJSX.EButton & JSXBase.HTMLAttributes<HTMLEButtonElement>;
            "e-input": LocalJSX.EInput & JSXBase.HTMLAttributes<HTMLEInputElement>;
            "e-link": LocalJSX.ELink & JSXBase.HTMLAttributes<HTMLELinkElement>;
            "e-list": LocalJSX.EList & JSXBase.HTMLAttributes<HTMLEListElement>;
            "e-list-item": LocalJSX.EListItem & JSXBase.HTMLAttributes<HTMLEListItemElement>;
            "e-select": LocalJSX.ESelect & JSXBase.HTMLAttributes<HTMLESelectElement>;
            "e-text": LocalJSX.EText & JSXBase.HTMLAttributes<HTMLETextElement>;
            "l-row": LocalJSX.LRow & JSXBase.HTMLAttributes<HTMLLRowElement>;
            "l-seperator": LocalJSX.LSeperator & JSXBase.HTMLAttributes<HTMLLSeperatorElement>;
            "l-spacer": LocalJSX.LSpacer & JSXBase.HTMLAttributes<HTMLLSpacerElement>;
            "p-info-item": LocalJSX.PInfoItem & JSXBase.HTMLAttributes<HTMLPInfoItemElement>;
            "p-node-card": LocalJSX.PNodeCard & JSXBase.HTMLAttributes<HTMLPNodeCardElement>;
            "p-node-item": LocalJSX.PNodeItem & JSXBase.HTMLAttributes<HTMLPNodeItemElement>;
            "v-catch-all": LocalJSX.VCatchAll & JSXBase.HTMLAttributes<HTMLVCatchAllElement>;
            "v-home": LocalJSX.VHome & JSXBase.HTMLAttributes<HTMLVHomeElement>;
        }
    }
}
