/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppRoot {
        "history": RouterHistory;
    }
    interface CBanner {
        "theme": string;
    }
    interface CCard {
    }
    interface CPage {
    }
    interface CSidebar {
    }
    interface CTest {
    }
    interface Demo20a {
        "history": RouterHistory;
    }
    interface Demo20b {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface EButton {
        "action": string;
        "active": boolean;
        "disabled": boolean;
        "size": string;
        "value": any;
        "variant": string;
    }
    interface EInput {
        "checked": boolean;
        "label": string;
        "name": string;
        "placeholder": string;
        "type": string;
        "value": string;
    }
    interface ELink {
        "action": string;
        "event": boolean;
        "href": string;
        "target": string;
        "theme": string;
        "value": any;
        "variant": string;
    }
    interface EList {
    }
    interface EListItem {
    }
    interface ESelect {
        "name": string;
        "options": any;
    }
    interface EText {
        "theme": string;
        "variant": string;
    }
    interface LRow {
        "align": string;
        "justifyContent": string;
        "variant": string;
    }
    interface LSeperator {
    }
    interface LSpacer {
        "value": number;
        "variant": string;
    }
    interface PBasicCard {
        "description": string;
        "explanation": string;
        "id": string;
        "isExpanded": boolean;
        "label": string;
        "question": string;
    }
    interface PBasicCard2 {
        "description": string;
        "id": string;
        "isExpanded": boolean;
        "label": string;
        "provocation": string;
        "references": string;
    }
    interface PCompactCard {
        "description": string;
        "explanation": string;
        "id": string;
        "label": string;
        "question": string;
    }
    interface PCompactCard2 {
        "description": string;
        "id": string;
        "label": string;
        "provocation": string;
        "references": string;
    }
    interface PCompactList {
        "stack": string;
    }
    interface PInfoItem {
    }
    interface PNodeCard {
        "isExpanded": boolean;
    }
    interface PNodeItem {
        "variant": string;
    }
    interface VCatchAll {
        "history": RouterHistory;
    }
    interface VHome {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCBannerElement extends Components.CBanner, HTMLStencilElement {
    }
    var HTMLCBannerElement: {
        prototype: HTMLCBannerElement;
        new (): HTMLCBannerElement;
    };
    interface HTMLCCardElement extends Components.CCard, HTMLStencilElement {
    }
    var HTMLCCardElement: {
        prototype: HTMLCCardElement;
        new (): HTMLCCardElement;
    };
    interface HTMLCPageElement extends Components.CPage, HTMLStencilElement {
    }
    var HTMLCPageElement: {
        prototype: HTMLCPageElement;
        new (): HTMLCPageElement;
    };
    interface HTMLCSidebarElement extends Components.CSidebar, HTMLStencilElement {
    }
    var HTMLCSidebarElement: {
        prototype: HTMLCSidebarElement;
        new (): HTMLCSidebarElement;
    };
    interface HTMLCTestElement extends Components.CTest, HTMLStencilElement {
    }
    var HTMLCTestElement: {
        prototype: HTMLCTestElement;
        new (): HTMLCTestElement;
    };
    interface HTMLDemo20aElement extends Components.Demo20a, HTMLStencilElement {
    }
    var HTMLDemo20aElement: {
        prototype: HTMLDemo20aElement;
        new (): HTMLDemo20aElement;
    };
    interface HTMLDemo20bElement extends Components.Demo20b, HTMLStencilElement {
    }
    var HTMLDemo20bElement: {
        prototype: HTMLDemo20bElement;
        new (): HTMLDemo20bElement;
    };
    interface HTMLEButtonElement extends Components.EButton, HTMLStencilElement {
    }
    var HTMLEButtonElement: {
        prototype: HTMLEButtonElement;
        new (): HTMLEButtonElement;
    };
    interface HTMLEInputElement extends Components.EInput, HTMLStencilElement {
    }
    var HTMLEInputElement: {
        prototype: HTMLEInputElement;
        new (): HTMLEInputElement;
    };
    interface HTMLELinkElement extends Components.ELink, HTMLStencilElement {
    }
    var HTMLELinkElement: {
        prototype: HTMLELinkElement;
        new (): HTMLELinkElement;
    };
    interface HTMLEListElement extends Components.EList, HTMLStencilElement {
    }
    var HTMLEListElement: {
        prototype: HTMLEListElement;
        new (): HTMLEListElement;
    };
    interface HTMLEListItemElement extends Components.EListItem, HTMLStencilElement {
    }
    var HTMLEListItemElement: {
        prototype: HTMLEListItemElement;
        new (): HTMLEListItemElement;
    };
    interface HTMLESelectElement extends Components.ESelect, HTMLStencilElement {
    }
    var HTMLESelectElement: {
        prototype: HTMLESelectElement;
        new (): HTMLESelectElement;
    };
    interface HTMLETextElement extends Components.EText, HTMLStencilElement {
    }
    var HTMLETextElement: {
        prototype: HTMLETextElement;
        new (): HTMLETextElement;
    };
    interface HTMLLRowElement extends Components.LRow, HTMLStencilElement {
    }
    var HTMLLRowElement: {
        prototype: HTMLLRowElement;
        new (): HTMLLRowElement;
    };
    interface HTMLLSeperatorElement extends Components.LSeperator, HTMLStencilElement {
    }
    var HTMLLSeperatorElement: {
        prototype: HTMLLSeperatorElement;
        new (): HTMLLSeperatorElement;
    };
    interface HTMLLSpacerElement extends Components.LSpacer, HTMLStencilElement {
    }
    var HTMLLSpacerElement: {
        prototype: HTMLLSpacerElement;
        new (): HTMLLSpacerElement;
    };
    interface HTMLPBasicCardElement extends Components.PBasicCard, HTMLStencilElement {
    }
    var HTMLPBasicCardElement: {
        prototype: HTMLPBasicCardElement;
        new (): HTMLPBasicCardElement;
    };
    interface HTMLPBasicCard2Element extends Components.PBasicCard2, HTMLStencilElement {
    }
    var HTMLPBasicCard2Element: {
        prototype: HTMLPBasicCard2Element;
        new (): HTMLPBasicCard2Element;
    };
    interface HTMLPCompactCardElement extends Components.PCompactCard, HTMLStencilElement {
    }
    var HTMLPCompactCardElement: {
        prototype: HTMLPCompactCardElement;
        new (): HTMLPCompactCardElement;
    };
    interface HTMLPCompactCard2Element extends Components.PCompactCard2, HTMLStencilElement {
    }
    var HTMLPCompactCard2Element: {
        prototype: HTMLPCompactCard2Element;
        new (): HTMLPCompactCard2Element;
    };
    interface HTMLPCompactListElement extends Components.PCompactList, HTMLStencilElement {
    }
    var HTMLPCompactListElement: {
        prototype: HTMLPCompactListElement;
        new (): HTMLPCompactListElement;
    };
    interface HTMLPInfoItemElement extends Components.PInfoItem, HTMLStencilElement {
    }
    var HTMLPInfoItemElement: {
        prototype: HTMLPInfoItemElement;
        new (): HTMLPInfoItemElement;
    };
    interface HTMLPNodeCardElement extends Components.PNodeCard, HTMLStencilElement {
    }
    var HTMLPNodeCardElement: {
        prototype: HTMLPNodeCardElement;
        new (): HTMLPNodeCardElement;
    };
    interface HTMLPNodeItemElement extends Components.PNodeItem, HTMLStencilElement {
    }
    var HTMLPNodeItemElement: {
        prototype: HTMLPNodeItemElement;
        new (): HTMLPNodeItemElement;
    };
    interface HTMLVCatchAllElement extends Components.VCatchAll, HTMLStencilElement {
    }
    var HTMLVCatchAllElement: {
        prototype: HTMLVCatchAllElement;
        new (): HTMLVCatchAllElement;
    };
    interface HTMLVHomeElement extends Components.VHome, HTMLStencilElement {
    }
    var HTMLVHomeElement: {
        prototype: HTMLVHomeElement;
        new (): HTMLVHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "c-banner": HTMLCBannerElement;
        "c-card": HTMLCCardElement;
        "c-page": HTMLCPageElement;
        "c-sidebar": HTMLCSidebarElement;
        "c-test": HTMLCTestElement;
        "demo-20a": HTMLDemo20aElement;
        "demo-20b": HTMLDemo20bElement;
        "e-button": HTMLEButtonElement;
        "e-input": HTMLEInputElement;
        "e-link": HTMLELinkElement;
        "e-list": HTMLEListElement;
        "e-list-item": HTMLEListItemElement;
        "e-select": HTMLESelectElement;
        "e-text": HTMLETextElement;
        "l-row": HTMLLRowElement;
        "l-seperator": HTMLLSeperatorElement;
        "l-spacer": HTMLLSpacerElement;
        "p-basic-card": HTMLPBasicCardElement;
        "p-basic-card-2": HTMLPBasicCard2Element;
        "p-compact-card": HTMLPCompactCardElement;
        "p-compact-card-2": HTMLPCompactCard2Element;
        "p-compact-list": HTMLPCompactListElement;
        "p-info-item": HTMLPInfoItemElement;
        "p-node-card": HTMLPNodeCardElement;
        "p-node-item": HTMLPNodeItemElement;
        "v-catch-all": HTMLVCatchAllElement;
        "v-home": HTMLVHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
        "history"?: RouterHistory;
    }
    interface CBanner {
        "theme"?: string;
    }
    interface CCard {
    }
    interface CPage {
    }
    interface CSidebar {
    }
    interface CTest {
    }
    interface Demo20a {
        "history"?: RouterHistory;
    }
    interface Demo20b {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface EButton {
        "action"?: string;
        "active"?: boolean;
        "disabled"?: boolean;
        "onButtonClick"?: (event: CustomEvent<any>) => void;
        "size"?: string;
        "value"?: any;
        "variant"?: string;
    }
    interface EInput {
        "checked"?: boolean;
        "label"?: string;
        "name"?: string;
        "onCheckboxInput"?: (event: CustomEvent<any>) => void;
        "onRadioInput"?: (event: CustomEvent<any>) => void;
        "onTextInput"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface ELink {
        "action"?: string;
        "event"?: boolean;
        "href"?: string;
        "onEvent_LinkClick"?: (event: CustomEvent<any>) => void;
        "target"?: string;
        "theme"?: string;
        "value"?: any;
        "variant"?: string;
    }
    interface EList {
    }
    interface EListItem {
    }
    interface ESelect {
        "name"?: string;
        "onEvent_selectInput"?: (event: CustomEvent<any>) => void;
        "options"?: any;
    }
    interface EText {
        "theme"?: string;
        "variant"?: string;
    }
    interface LRow {
        "align"?: string;
        "justifyContent"?: string;
        "variant"?: string;
    }
    interface LSeperator {
    }
    interface LSpacer {
        "value"?: number;
        "variant"?: string;
    }
    interface PBasicCard {
        "description"?: string;
        "explanation"?: string;
        "id"?: string;
        "isExpanded"?: boolean;
        "label"?: string;
        "onDeleteCardEvent"?: (event: CustomEvent<any>) => void;
        "question"?: string;
    }
    interface PBasicCard2 {
        "description"?: string;
        "id"?: string;
        "isExpanded"?: boolean;
        "label"?: string;
        "onDeleteCardEvent"?: (event: CustomEvent<any>) => void;
        "provocation"?: string;
        "references"?: string;
    }
    interface PCompactCard {
        "description"?: string;
        "explanation"?: string;
        "id"?: string;
        "label"?: string;
        "onDeleteCardEvent"?: (event: CustomEvent<any>) => void;
        "question"?: string;
    }
    interface PCompactCard2 {
        "description"?: string;
        "id"?: string;
        "label"?: string;
        "onDeleteCardEvent"?: (event: CustomEvent<any>) => void;
        "onShowModal"?: (event: CustomEvent<any>) => void;
        "provocation"?: string;
        "references"?: string;
    }
    interface PCompactList {
        "onDeleteAllCardsEvent"?: (event: CustomEvent<any>) => void;
        "stack"?: string;
    }
    interface PInfoItem {
    }
    interface PNodeCard {
        "isExpanded"?: boolean;
    }
    interface PNodeItem {
        "variant"?: string;
    }
    interface VCatchAll {
        "history"?: RouterHistory;
    }
    interface VHome {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "c-banner": CBanner;
        "c-card": CCard;
        "c-page": CPage;
        "c-sidebar": CSidebar;
        "c-test": CTest;
        "demo-20a": Demo20a;
        "demo-20b": Demo20b;
        "e-button": EButton;
        "e-input": EInput;
        "e-link": ELink;
        "e-list": EList;
        "e-list-item": EListItem;
        "e-select": ESelect;
        "e-text": EText;
        "l-row": LRow;
        "l-seperator": LSeperator;
        "l-spacer": LSpacer;
        "p-basic-card": PBasicCard;
        "p-basic-card-2": PBasicCard2;
        "p-compact-card": PCompactCard;
        "p-compact-card-2": PCompactCard2;
        "p-compact-list": PCompactList;
        "p-info-item": PInfoItem;
        "p-node-card": PNodeCard;
        "p-node-item": PNodeItem;
        "v-catch-all": VCatchAll;
        "v-home": VHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "c-banner": LocalJSX.CBanner & JSXBase.HTMLAttributes<HTMLCBannerElement>;
            "c-card": LocalJSX.CCard & JSXBase.HTMLAttributes<HTMLCCardElement>;
            "c-page": LocalJSX.CPage & JSXBase.HTMLAttributes<HTMLCPageElement>;
            "c-sidebar": LocalJSX.CSidebar & JSXBase.HTMLAttributes<HTMLCSidebarElement>;
            "c-test": LocalJSX.CTest & JSXBase.HTMLAttributes<HTMLCTestElement>;
            "demo-20a": LocalJSX.Demo20a & JSXBase.HTMLAttributes<HTMLDemo20aElement>;
            "demo-20b": LocalJSX.Demo20b & JSXBase.HTMLAttributes<HTMLDemo20bElement>;
            "e-button": LocalJSX.EButton & JSXBase.HTMLAttributes<HTMLEButtonElement>;
            "e-input": LocalJSX.EInput & JSXBase.HTMLAttributes<HTMLEInputElement>;
            "e-link": LocalJSX.ELink & JSXBase.HTMLAttributes<HTMLELinkElement>;
            "e-list": LocalJSX.EList & JSXBase.HTMLAttributes<HTMLEListElement>;
            "e-list-item": LocalJSX.EListItem & JSXBase.HTMLAttributes<HTMLEListItemElement>;
            "e-select": LocalJSX.ESelect & JSXBase.HTMLAttributes<HTMLESelectElement>;
            "e-text": LocalJSX.EText & JSXBase.HTMLAttributes<HTMLETextElement>;
            "l-row": LocalJSX.LRow & JSXBase.HTMLAttributes<HTMLLRowElement>;
            "l-seperator": LocalJSX.LSeperator & JSXBase.HTMLAttributes<HTMLLSeperatorElement>;
            "l-spacer": LocalJSX.LSpacer & JSXBase.HTMLAttributes<HTMLLSpacerElement>;
            "p-basic-card": LocalJSX.PBasicCard & JSXBase.HTMLAttributes<HTMLPBasicCardElement>;
            "p-basic-card-2": LocalJSX.PBasicCard2 & JSXBase.HTMLAttributes<HTMLPBasicCard2Element>;
            "p-compact-card": LocalJSX.PCompactCard & JSXBase.HTMLAttributes<HTMLPCompactCardElement>;
            "p-compact-card-2": LocalJSX.PCompactCard2 & JSXBase.HTMLAttributes<HTMLPCompactCard2Element>;
            "p-compact-list": LocalJSX.PCompactList & JSXBase.HTMLAttributes<HTMLPCompactListElement>;
            "p-info-item": LocalJSX.PInfoItem & JSXBase.HTMLAttributes<HTMLPInfoItemElement>;
            "p-node-card": LocalJSX.PNodeCard & JSXBase.HTMLAttributes<HTMLPNodeCardElement>;
            "p-node-item": LocalJSX.PNodeItem & JSXBase.HTMLAttributes<HTMLPNodeItemElement>;
            "v-catch-all": LocalJSX.VCatchAll & JSXBase.HTMLAttributes<HTMLVCatchAllElement>;
            "v-home": LocalJSX.VHome & JSXBase.HTMLAttributes<HTMLVHomeElement>;
        }
    }
}
